---
kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:14-alpine
    commands:
      - cd website
      - apk add python3 make g++
      - npm install
      - npm run build
---
kind: pipeline
type: docker
name: promote

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: Generate
    image: node:14-alpine
    commands:
      - cd website
      - apk add python3 make g++
      - npm install
      - npm run generate
  - name: Zip
    image: alpine:latest
    commands:
      - cd website
      - apk add zip
      - mkdir website
      - cd dist
      - zip -r ../website/dist.zip *
  - name: Upload to S3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: 
        from_secret: s3Access
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3Secret
      AWS_DEFAULT_REGION: eu-west-2
      AMP_WEBSITE_APP_ID:
        from_secret: ampId
    commands:
      - cd website
      - aws s3api put-object --bucket bradley-chatha --key website/dist.zip --body website/dist.zip
  - name: Create hosts file
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY:
        from_secret: s3Access
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3Secret
      INSTANCE_ID:
        from_secret: instanceId
    commands:
      - cd website
      - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
      - yum install -y session-manager-plugin.rpm
      - yum install -y ansible
      - echo server ansible_connection=aws_ssm ansible_aws_ssm_instance_id=$INSTANCE_ID ansible_aws_ssm_bucket_name=bradley-chatha ansible_aws_ssm_region=eu-west-2 ansible_aws_ssm_plugin=/usr/bin/session-manager-plugin > hosts
      - ansible-playbook playbook.yml -i ./hosts -t deploy