---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: Build
    image: node:14-alpine
    commands:
      - cd website
      - apk add python3 make g++
      - npm install
      - npm run build
      - npm run generate
  - name: Upload to Docker
    image: plugins/docker
    settings:
      username:
          from_secret: DOCKER_USERNAME
      password:
          from_secret: DOCKER_PASSWORD
      repo: bradleychatha/website
      tags: latest
      dockerfile: website/Dockerfile
  - name: Trigger deployment
    image: hendrikmaus/nomad-cli:latest
    environment:
      NOMAD_ADDR:
        from_secret: NOMAD_ADDR
      NOMAD_TOKEN:
        from_secret: NOMAD_TOKEN
    commands:
      - cd website
      - nomad stop personal
      - nomad run service.nomad
