---
kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:14-alpine
    commands:
      - cd website
      - apk add python3 make g++
      - npm install
      - npm run build
---
kind: pipeline
type: docker
name: promote

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: Generate
    image: node:14-alpine
    commands:
      - cd website
      - apk add python3 make g++
      - npm install
      - npm run generate
  - name: Upload to Docker
    image: plugins/docker
    settings:
      username:
          from_secret: DOCKER_USERNAME
      password:
          from_secret: DOCKER_PASSWORD
      repo: bradleychatha/website
      tags: latest
    when:
      branch:
        - master
  - name: Trigger deployment
    image: hendrikmaus/nomad-cli:latest
    environment:
      NOMAD_ADDR:
        from_secret: NOMAD_ADDR
      NOMAD_TOKEN:
        from_secret: NOMAD_TOKEN
    commands:
      - nomad run service.nomad
    when:
      branch:
        - master
