---
- name: Deploy
  hosts: server
  tags:
    - deploy
  tasks:
    - name: Download
      aws_s3:
        bucket: bradley-chatha
        object: /website/dist.zip
        dest: /var/www/personal/dist.zip
        region: eu-west-2
        mode: get
    - name: Unzip
      unarchive:
        src: /var/www/personal/dist.zip
        dest: /var/www/personal/
    - name: Run
      docker_container:
        name: bchttpd_personal
        image: bradleychatha/bchttpd
        volumes:
          - /var/www/personal:/var/www
        ports:
          - 9080:8080
          - 9081:8081
        restart_policy: always
        recreate: true
        state: started
        pull: true