name: Upload to AWS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
        run: cd website
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
      
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Generate
        run: npm run generate
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: dist.zip
          directory: dist/
          
      - name: Setup upload directory
        run: |
          mkdir website
          cp dist/dist.zip website/dist.zip
          
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: eu-west-2
          
      - name: Upload to S3
        run: aws s3api put-object --bucket bradley-chatha --key website/dist.zip --body website/dist.zip
